language: go

go:
  - 1.7.1
  - tip

sudo: true

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y && sudo apt-get update -q
  - sudo apt-get install glide -y
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

before_script:
  - make deps

script:
  - make test
  - make vet
  - make fmt
  - make lint
